# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_groups_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('profile', models.CharField(choices=[('Senior_Manager', 'Senior_Manager'), ('Junior_Manager', 'Junior_Manager'), ('Clerk', 'Clerk'), ('Guard', 'Guard')], max_length=20)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'employee_record',
                'managed': True,
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
