# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_groups_app', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'bookauthor',
                'managed': True,
                'verbose_name_plural': 'Book_Author',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_groups_app.Book_Author'),
        ),
    ]
