# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_groups_app', '0004_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
