# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_groups_app', '0006_auto_20180913_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/book_image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
